### ISSUE TITLE
How synchronized ith nngpp with nng?

### ISSUE THREAD

**Issue by fhajji** [cwzx/nngpp#12]
Hello,
the last release of nngpp is 1.1.1, but nng itself is already at 1.2.3, with [1.3.0 just around the corner](https://github.com/nanomsg/nng/commit/1b811f68eb0294e947c7b775fd24a239bb44b5b8). So how compatible is nngpp with current nng? Right now, I'm using nngpp-1.1.1 with nng-1.1.1, and I would like to upgrade nng without too much breakage.
Thanks.

**Comment by cwzx** [comment]
Tag added for v1.2.4
nngpp master is up to date with nng master
