### ISSUE TITLE
std::string based buffer?

### ISSUE THREAD

**Issue by dpellegr** [cwzx/nngpp#15]
Why are buffer and view based on cstring instead of std::string?
I am thinking about wrapping or refactoring them, would it be good?

Thanks for the advice!

**Comment by cwzx** [comment]
Because message data may not be strings. It could be binary data that will be deserialized into a data structure. It would not be appropriate to use std::string for such data.

Also, putting each message's data into a std::string would cost an extra allocation and copy. If your application has string data, a better approach is to use std::string_view to process the raw message before discarding or reusing the message buffer if possible.

**Comment by dpellegr** [comment]
My point is that also cstring stretches the appropriateness of holding random binary data. With respect to that, a std::string + reinterpret_cast is only adding automatic memory management. 

See https://stackoverflow.com/questions/441203/proper-way-to-store-binary-data-with-c-stl

Superfluous allocations and copies can easily be avoided with the move semantics, which basically only swap a pointer while still enforcing RAII.

I was not familiar with std::string_view. I think that it does a great job enabling C++ features on literals and cstrings, but still it does not solve the issues with memory ownership and management.

**Comment by cwzx** [comment]
nngpp is already 100% RAII + move enabled, including the nng::buffer. There are no "issues" with memory management or ownership, that is the whole point of nngpp.

The key here is we are interfacing with nng, which is not a C++ library. **There is no way to "move" a std::string into a C library.**

In particular, std::string is not able to:
* Take ownership of an existing allocation (receive data from nng without copying it)
* Release ownership of a contained allocation (give data to nng without copying it)

This is why we have nng::buffer.

**Comment by dpellegr** [comment]
> This is why we have nng::buffer.

Crystal clear! Thank you for the explanation and for the string_view advice.

**Comment by ed-aka-yaboi** [comment]
A follow up question. How can I access the contents of a message body in my application? I'm working with strings and integers.

**Comment by cwzx** [comment]
See https://github.com/cwzx/nngpp/blob/master/test/message.cpp
