### ISSUE TITLE
Error setting reconnect_time_min

### ISSUE THREAD

**Issue by amunhoz** [cwzx/nngpp#19]
nng 1.3.0
protocol pair:v1
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 

code:
sockx->set_opt_ms(nng::to_name(nng::option::reconnect_time_min), (nng_duration)1000);

throws
test: malloc.c:2401: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
Aborted (core dumped)

**Comment by cwzx** [comment]
This kind of error is caused by a memory corruption bug in your code.
