### ISSUE TITLE
Changing the listening address

### ISSUE THREAD

**Issue by dpellegr** [cwzx/nngpp#22]
Not really an issue, just a question :)

If I do:

```
socket.listen(somePath);
...
socket.listen(newPath);
```
do I need to do anything to release the listener (eg. `socket = nng::something::open`) or is it ok to directly call `listen` the second time?

**Comment by cwzx** [comment]
Yes you need to close the existing listener. Two options:

1. As you suggested: Destroy the socket, which will close the existing listener, and replace with a new one.

2. Use an explicit listener:
```cpp
auto socket = ...

// instead of socket.listen
auto listener = nng::listener(socket, "some_path", 0);

// close the old listener, replacing with a new one
listener = nng::listener(socket, "new_path", 0);
```

**Comment by dpellegr** [comment]
Thank you!

By peeking at the source I confirmed my suspect that a second call to `listen` would leak the previous listener. I don't think that properly written C++ should allow that (smart pointers?) but this is quite a corner case so this gotcha should not catch many others...

Both the provided solution works for me.

**Comment by cwzx** [comment]
> By peeking at the source I confirmed my suspect that a second call to `listen` would leak the previous listener. I don't think that properly written C++ should allow that (smart pointers?) but this is quite a corner case so this gotcha should not catch many others...

This is not true.
Calling sock.listen() a second time results in two listeners associated with the socket (many to one relation).
Both are destroyed when the socket is closed. Nothing is leaked.
This is fine if you are ok with both being active.

**Comment by dpellegr** [comment]
> Calling sock.listen() a second time results in two listeners associated with the socket (many to one relation).
> Both are destroyed when the socket is closed. Nothing is leaked.
> This is fine if you are ok with both being active.

Thanks for the clarification.
