### ISSUE TITLE
nng::socket_view::recv is missing an overload for nng::view

### ISSUE THREAD

**Issue by gregorburger** [cwzx/nngpp#4]
I needed to wrap pre-allocated memory into a buffer which i did with `nng::view( T* d, size_t s )` because `nng::buffer( T* d, size_t s)` will free the pointer to d so i will get double free. But unfortunately `nng::socket_view::recv` has no overload for `nng::view` only for `nng::buffer`.

**Comment by cwzx** [comment]
[Done](https://github.com/cwzx/nngpp/commit/907d1199f1e1e4d8e683c76936ef2f56af070d60)
