### ISSUE TITLE
error: dialer_view.h(38): error C3861: 'nng_dialer_set': identifier not found

### ISSUE THREAD

**Issue by McKillroy** [cwzx/nngpp#7]
I am getting the following error:
\include\nngpp\dialer_view.h(38): error C3861: 'nng_dialer_set': identifier not found

I can find this identifier with fulltext search neither in the nng git nor in nngpp.

Am I missing something or this just so much WiP that it is supposed to be broken?

Cheers
~Y.

**Comment by McKillroy** [comment]
Just learned I'd need to use nng master instead of the 1.1.1 tagged release - would be nice to have nngpp tagged releases so it becomes clear which version of nngpp is supposed to work with which version of nng.

**Comment by cwzx** [comment]
Tag added for nng-v1.1.1

**Comment by McKillroy** [comment]
With this help I could finally build the demos and perf examples and link them against nng 1.1.1 with a custom CMakeLists.txt.
I will now wait for the next release of nng and then check out nngpp for our own work - in the moment I am still using nng directly.
It's really helpful to have these matched tags - thank you !
